from app.models.roles import Rol
from app.models.usuarios import Usuario
from app.models.rutas import Ruta
from app.models.tareas import Tarea
from app.models.guias import Guia
from app.models.progreso import Progreso
from app.models.preguntas_ia import PreguntaIA
from app.models.actividad import Actividad
from app.models.alertas import Alerta
from app.models.categorias_soporte import CategoriaSoporte
from app.models.soporte import Soporte
from app.models.integracion_bit24 import IntegracionBit24
